/*
Suppression des tables
*/

DROP TABLE CLASSER_UTILISATEUR_EPREUVE;
DROP TABLE CLASSER_EQUIPE_EPREUVE;
DROP TABLE CLASSER;
DROP TABLE CLASSEMENT;
DROP TABLE ASSOCIER;
DROP TABLE CHRONOMETRER;
DROP TABLE PARTICIPER;
DROP TABLE EPREUVE;
DROP TABLE TYPEEPREUVE;
DROP TABLE COMPETITION;
DROP TABLE TYPECOMPETITION;
DROP TABLE PIECEJOINTE;
DROP TABLE APPARTENIR;
DROP TABLE UTILISATEUR;
DROP TABLE ROLEEQUIPE;
DROP TABLE EQUIPE;
DROP TABLE TYPEPIECEJOINTE;
DROP TABLE GENRE;
DROP TABLE RANG;
DROP TABLE CATEGORIE;

/*
Suppression des sequences
*/

DROP SEQUENCE SEQ_UTILISATEUR_ID_UTILISATEUR;
DROP SEQUENCE SEQ_RANG_ID_RANG;
DROP SEQUENCE SEQ_PIECEJOINTE_ID_PIECEJOINTE;
DROP SEQUENCE SEQ_TYPEPIECEJ_ID_TYPEPIECEJ;
DROP SEQUENCE SEQ_EQUIPE_ID_EQUIPE;
DROP SEQUENCE SEQ_ROLEEQUIPE_ID_ROLEEQUIPE;
DROP SEQUENCE SEQ_TYPECOMP_ID_TYPECOMP;
DROP SEQUENCE SEQ_COMPETITION_ID_COMPETITION;
DROP SEQUENCE SEQ_TYPEEPREUVE_ID_TYPEEPREUVE;
DROP SEQUENCE SEQ_EPREUVE_ID_EPREUVE;
DROP SEQUENCE SEQ_GENRE_ID_GENRE;
DROP SEQUENCE SEQ_CATEGORIE_ID_CATEGORIE;
DROP SEQUENCE SEQ_CLASSEMENT_ID_CLASSEMENT;

/*
Table: CATEGORIE
*/

CREATE TABLE CATEGORIE(
    ID_CATEGORIE NUMBER(10,0) NOT NULL ,
    LIBELLE      VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (ID_CATEGORIE)
);

/*
Table: RANG
*/

CREATE TABLE RANG(
    ID_RANG NUMBER NOT NULL ,
    LIBELLE VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_RANG PRIMARY KEY (ID_RANG)
);

/*
Table: GENRE
*/

CREATE TABLE GENRE(
    ID_GENRE NUMBER(10,0) NOT NULL ,
    LIBELLE  VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_GENRE PRIMARY KEY (ID_GENRE)
);

/*
Table: TYPEPIECEJOINTE
*/

CREATE TABLE TYPEPIECEJOINTE(
    ID_TYPEPIECEJOINTE NUMBER(10,0) NOT NULL ,
    LIBELLE            VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_TYPEPIECEJOINTE PRIMARY KEY (ID_TYPEPIECEJOINTE)
);

/*
Table: EQUIPE
*/

CREATE TABLE EQUIPE(
    ID_EQUIPE NUMBER(10,0) NOT NULL ,
    NOM       VARCHAR2(50) NOT NULL ,
    CODE      VARCHAR2(10) ,
    VALIDE    CHAR(1) NOT NULL ,
    CONSTRAINT PK_EQUIPE PRIMARY KEY (ID_EQUIPE)
);

/*
Table: ROLEEQUIPE
*/

CREATE TABLE ROLEEQUIPE(
    ID_ROLEEQUIPE NUMBER(10,0) NOT NULL ,
    LIBELLE       VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_ROLEEQUIPE PRIMARY KEY (ID_ROLEEQUIPE)
);

/*
Table: UTILISATEUR
*/

CREATE TABLE UTILISATEUR(
    ID_UTILISATEUR NUMBER(10,0) NOT NULL ,
    NOM            VARCHAR2(50) NOT NULL CONSTRAINT NOM_MAJUSCULE CHECK(NOM=UPPER(NOM)),
    PRENOM         VARCHAR2(50) NOT NULL CONSTRAINT PRENOM_MAJUSCULE_INITCAP CHECK(PRENOM=INITCAP(PRENOM)),
    DATENAISSANCE  DATE NOT NULL ,
    NUMTELEPHONE   VARCHAR2(50) NOT NULL ,
    CLUB           VARCHAR2(50) ,
    EMAIL          VARCHAR2(50) NOT NULL CONSTRAINT EMAIL_UNIQUE UNIQUE,
    CODEPOSTAL     VARCHAR2(50) NOT NULL ,
    VILLE          VARCHAR2(50) NOT NULL ,
    ADRESSE        VARCHAR2(50) NOT NULL ,
    MOTDEPASSE     CHAR(64) NOT NULL ,
    ID_GENRE       NUMBER(10,0) NOT NULL ,
    ID_RANG        NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY (ID_UTILISATEUR) ,
    CONSTRAINT FK_UTILISATEUR_GENRE FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE) ,
    CONSTRAINT FK_UTILISATEUR_RANG FOREIGN KEY (ID_RANG) REFERENCES RANG(ID_RANG)
);

/*
Table: APPARTENIR
*/
CREATE TABLE APPARTENIR(
    ID_UTILISATEUR NUMBER(10,0) NOT NULL ,
    ID_EQUIPE NUMBER(10,0) NOT NULL ,
    ID_ROLEEQUIPE NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_APPARTENIR PRIMARY KEY (ID_UTILISATEUR, ID_EQUIPE) ,
    CONSTRAINT FK_APPARTENIR_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_APPARTENIR_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ,
    CONSTRAINT FK_APPARTENIR_ROLEEQUIPE FOREIGN KEY (ID_ROLEEQUIPE) REFERENCES ROLEEQUIPE(ID_ROLEEQUIPE)
);

/*
Table: PIECEJOINTE
*/

CREATE TABLE PIECEJOINTE(
    ID_PIECEJOINTE     NUMBER(10,0) NOT NULL ,
    LIBELLE            VARCHAR2(50) NOT NULL ,
    CHEMIN             VARCHAR2(50) NOT NULL ,
    ID_UTILISATEUR     NUMBER(10,0) NOT NULL ,
    ID_TYPEPIECEJOINTE NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_PIECEJOINTE PRIMARY KEY (ID_PIECEJOINTE) ,
    CONSTRAINT FK_PIECEJOINTE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_PIECEJOINTE_ROLEEQUIPE FOREIGN KEY (ID_TYPEPIECEJOINTE) REFERENCES ROLEEQUIPE(ID_ROLEEQUIPE)
);

/*
Table: TYPECOMPETITION
*/

CREATE TABLE TYPECOMPETITION(
    ID_TYPECOMPETITION NUMBER(10,0) NOT NULL ,
    LIBELLE            VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_TYPECOMPETITION PRIMARY KEY (ID_TYPECOMPETITION)
);

/*
Table: COMPETITION
*/

CREATE TABLE COMPETITION(
    ID_COMPETITION     NUMBER(10,0) NOT NULL ,
    NOM                VARCHAR2(50) NOT NULL ,
    DATEFININSCRIPTION DATE NOT NULL ,
    DATEDEBUT          DATE NOT NULL ,
    ID_TYPECOMPETITION NUMBER(10,0) NOT NULL ,
    ID_CATEGORIE       NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_COMPETITION PRIMARY KEY (ID_COMPETITION),
    CONSTRAINT FK_COMPETITION_TYPECOMPETITION FOREIGN KEY (ID_TYPECOMPETITION) REFERENCES TYPECOMPETITION(ID_TYPECOMPETITION)
);

/*
Table: TYPEEPREUVE
*/

CREATE TABLE TYPEEPREUVE(
    ID_TYPEEPREUVE NUMBER(10,0) NOT NULL ,
    LIBELLE        VARCHAR2(50) NOT NULL ,
    CONSTRAINT PK_TYPEEPREUVE PRIMARY KEY (ID_TYPEEPREUVE)
);

/*
Table: EPREUVE
*/

CREATE TABLE EPREUVE(
    ID_EPREUVE     NUMBER(10,0) NOT NULL ,
    ORDRE          NUMBER(10,0) NOT NULL ,
    ID_TYPEEPREUVE NUMBER(10,0) NOT NULL ,
    ID_COMPETITION NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_EPREUVE PRIMARY KEY (ID_EPREUVE) ,
    CONSTRAINT FK_EPREUVE_TYPEEPREUVE FOREIGN KEY (ID_TYPEEPREUVE) REFERENCES TYPEEPREUVE(ID_TYPEEPREUVE) ,
    CONSTRAINT FK_EPREUVE_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION)
);

/*
Table: PARTICIPER
*/

CREATE TABLE PARTICIPER(
    ID_COMPETITION NUMBER(10,0) NOT NULL ,
    ID_EQUIPE      NUMBER(10,0) NOT NULL ,
    SCORE          NUMBER(10,0) NOT NULL ,
    TEMPS          NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_PARTICIPER PRIMARY KEY (ID_COMPETITION, ID_EQUIPE) ,
    CONSTRAINT FK_PARTICIPER_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION) ,
    CONSTRAINT FK_PARTICIPER_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE)
);

/*
Table: CHRONOMETRER
*/

CREATE TABLE CHRONOMETRER(
    ID_UTILISATEUR NUMBER(10,0) NOT NULL ,
    ID_EPREUVE     NUMBER(10,0) NOT NULL ,
    TEMPS          NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_CHRONOMETRER PRIMARY KEY (ID_UTILISATEUR, ID_EPREUVE) ,
    CONSTRAINT FK_CHRONOMETRER_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_CHRONOMETRER_EPREUVE FOREIGN KEY (ID_EPREUVE) REFERENCES EPREUVE(ID_EPREUVE)
);

/*
Table: ASSOCIER
*/

CREATE TABLE ASSOCIER(
    DOSSARD        NUMBER(10,0) ,
    PUCE           NUMBER(10,0) ,
    ID_UTILISATEUR NUMBER(10,0) NOT NULL ,
    ID_COMPETITION NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_ASSOCIER PRIMARY KEY (ID_UTILISATEUR, ID_COMPETITION) ,
    CONSTRAINT FK_ASSOCIER_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_ASSOCIER_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION)
);

/*
Table: CLASSEMENT
*/

CREATE TABLE CLASSEMENT(
    ID_CLASSEMENT NUMBER(10,0) NOT NULL ,
    LIBELLE       VARCHAR2(255) NOT NULL ,
    CONSTRAINT PK_CLASSEMENT PRIMARY KEY (ID_CLASSEMENT)
);

/*
Table: CLASSER
*/

CREATE TABLE CLASSER(
    ID_EQUIPE     NUMBER(10,0) NOT NULL ,
    ID_CLASSEMENT NUMBER(10,0) NOT NULL ,
    POSITION      NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_CLASSER PRIMARY KEY (ID_EQUIPE, ID_CLASSEMENT),
    CONSTRAINT FK_CLASSER_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_CLASSER_CLASSEMENT FOREIGN KEY (ID_CLASSEMENT) REFERENCES CLASSEMENT(ID_CLASSEMENT)
);

/*
Table: CLASSER_EQUIPE_EPREUVE
*/

CREATE TABLE CLASSER_EQUIPE_EPREUVE(
    ID_EQUIPE     NUMBER(10,0) NOT NULL ,
    ID_EPREUVE    NUMBER(10,0) NOT NULL ,
    TEMPS         NUMBER(10,0) NOT NULL ,
    POSITION      NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_CLASSER_EQUIPE_EPREUVE PRIMARY KEY (ID_EQUIPE, ID_EPREUVE),
    CONSTRAINT FK_CEE_EQ FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_CEE_EP FOREIGN KEY (ID_EPREUVE) REFERENCES EPREUVE(ID_EPREUVE)
);

/*
Table: CLASSER_PARTICIPANT_EPREUVE
*/

CREATE TABLE CLASSER_UTILISATEUR_EPREUVE(
    ID_UTILISATEUR  NUMBER(10,0) NOT NULL ,
    ID_EPREUVE      NUMBER(10,0) NOT NULL ,
    TEMPS           NUMBER(10,0) NOT NULL ,
    POSITION        NUMBER(10,0) NOT NULL ,
    CONSTRAINT PK_CPE PRIMARY KEY (ID_UTILISATEUR, ID_EPREUVE),
    CONSTRAINT FK_CUE_U FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_CUE_E FOREIGN KEY (ID_EPREUVE) REFERENCES EPREUVE(ID_EPREUVE)
);

/*
Sequences
*/

CREATE SEQUENCE SEQ_UTILISATEUR_ID_UTILISATEUR START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_RANG_ID_RANG START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_PIECEJOINTE_ID_PIECEJOINTE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_TYPEPIECEJ_ID_TYPEPIECEJ START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_EQUIPE_ID_EQUIPE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_ROLEEQUIPE_ID_ROLEEQUIPE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_TYPECOMP_ID_TYPECOMP START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_COMPETITION_ID_COMPETITION START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_TYPEEPREUVE_ID_TYPEEPREUVE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_EPREUVE_ID_EPREUVE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_GENRE_ID_GENRE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIE_ID_CATEGORIE START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SEQ_CLASSEMENT_ID_CLASSEMENT START WITH 1 INCREMENT BY 1 NOCYCLE;

/*
Triggers
*/

CREATE OR REPLACE TRIGGER TRIGGERUTILISATEUR
BEFORE INSERT OR UPDATE ON UTILISATEUR 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_UTILISATEUR_ID_UTILISATEUR.NEXTVAL INTO :NEW.ID_UTILISATEUR FROM DUAL;
    elsif updating then
        :NEW.ID_UTILISATEUR:=:OLD.ID_UTILISATEUR;
    end if;
    :NEW.NOM:=UPPER(:NEW.NOM);
    :NEW.PRENOM:=INITCAP(:NEW.PRENOM);
    if :NEW.ID_RANG IS NULL then
        :NEW.ID_RANG:=1;
    end if;
END;
/

CREATE OR REPLACE TRIGGER RANG_ID_RANG
BEFORE INSERT OR UPDATE ON RANG 
FOR EACH ROW 
BEGIN
    if inserting then
        SELECT SEQ_RANG_ID_RANG.NEXTVAL INTO :NEW.ID_RANG FROM DUAL;
    elsif updating then 
        :NEW.ID_RANG:=:OLD.ID_RANG;
    end if;
END;
/

CREATE OR REPLACE TRIGGER PIECEJOINTE_ID_PIECEJOINTE
BEFORE INSERT OR UPDATE ON PIECEJOINTE 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_PIECEJOINTE_ID_PIECEJOINTE.NEXTVAL INTO :NEW.ID_PIECEJOINTE FROM DUAL;
    elsif updating then
        :NEW.ID_PIECEJOINTE:=:OLD.ID_PIECEJOINTE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TYPEPIECEJ_ID_TYPEPIECEJ
BEFORE INSERT OR UPDATE ON TYPEPIECEJOINTE 
FOR EACH ROW 
BEGIN
    if inserting then 
	    SELECT SEQ_TYPEPIECEJ_ID_TYPEPIECEJ.NEXTVAL INTO :NEW.ID_TYPEPIECEJOINTE FROM DUAL; 
    elsif updating then
        :NEW.ID_TYPEPIECEJOINTE:=:OLD.ID_TYPEPIECEJOINTE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TRIGGEREQUIPE
BEFORE INSERT OR UPDATE ON EQUIPE 
FOR EACH ROW
BEGIN
    if inserting then 
	    SELECT SEQ_EQUIPE_ID_EQUIPE.NEXTVAL INTO :NEW.ID_EQUIPE FROM DUAL;
        SELECT dbms_random.string('A', 10) INTO :NEW.CODE FROM DUAL;
        :NEW.VALIDE:=0;
    elsif updating then 
        :NEW.ID_EQUIPE:=:OLD.ID_EQUIPE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER ROLEEQUIPE_ID_ROLEEQUIPE
BEFORE INSERT OR UPDATE ON ROLEEQUIPE 
FOR EACH ROW 
BEGIN
    if inserting then 
    	SELECT SEQ_ROLEEQUIPE_ID_ROLEEQUIPE.NEXTVAL INTO :NEW.ID_ROLEEQUIPE FROM DUAL;
    elsif updating then 
        :NEW.ID_ROLEEQUIPE:=:OLD.ID_ROLEEQUIPE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TYPECOMP_ID_TYPECOMP
BEFORE INSERT OR UPDATE ON TYPECOMPETITION 
FOR EACH ROW 
BEGIN
    if inserting then 
	    SELECT SEQ_TYPECOMP_ID_TYPECOMP.NEXTVAL INTO :NEW.ID_TYPECOMPETITION FROM DUAL;
    elsif updating then 
        :NEW.ID_TYPECOMPETITION:=:OLD.ID_TYPECOMPETITION;
    end if;
END;
/

CREATE OR REPLACE TRIGGER COMPETITION_ID_COMPETITION
BEFORE INSERT OR UPDATE ON COMPETITION 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_COMPETITION_ID_COMPETITION.NEXTVAL INTO :NEW.ID_COMPETITION FROM DUAL;
    elsif updating then 
        :NEW.ID_COMPETITION:=:OLD.ID_COMPETITION;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TYPEEPREUVE_ID_TYPEEPREUVE
BEFORE INSERT OR UPDATE ON TYPEEPREUVE 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_TYPEEPREUVE_ID_TYPEEPREUVE.NEXTVAL INTO :NEW.ID_TYPEEPREUVE FROM DUAL;
    elsif updating then 
        :NEW.ID_TYPEEPREUVE:=:OLD.ID_TYPEEPREUVE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER EPREUVE_ID_EPREUVE
BEFORE INSERT OR UPDATE ON EPREUVE 
FOR EACH ROW 
BEGIN
    if inserting then 
	    SELECT SEQ_EPREUVE_ID_EPREUVE.NEXTVAL INTO :NEW.ID_EPREUVE FROM DUAL;
    elsif updating then 
        :NEW.ID_EPREUVE:=:OLD.ID_EPREUVE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER GENRE_ID_GENRE
BEFORE INSERT OR UPDATE ON GENRE 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_GENRE_ID_GENRE.NEXTVAL INTO :NEW.ID_GENRE FROM DUAL; 
    elsif updating then 
        :NEW.ID_GENRE:=:OLD.ID_GENRE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER CATEGORIE_ID_CATEGORIE
BEFORE INSERT OR UPDATE ON CATEGORIE 
FOR EACH ROW 
BEGIN
    if inserting then 
        SELECT SEQ_CATEGORIE_ID_CATEGORIE.NEXTVAL INTO :NEW.ID_CATEGORIE FROM DUAL;
    elsif updating then 
        :NEW.ID_CATEGORIE:=:OLD.ID_CATEGORIE;
    end if;
END;
/

CREATE OR REPLACE TRIGGER CLASSEMENT_ID_CLASSEMENT
BEFORE INSERT OR UPDATE ON CLASSEMENT 
FOR EACH ROW 
BEGIN
    if inserting then
        SELECT SEQ_CLASSEMENT_ID_CLASSEMENT.NEXTVAL INTO :NEW.ID_CLASSEMENT FROM DUAL;
    elsif updating then
        :NEW.ID_CLASSEMENT:=:OLD.ID_CLASSEMENT;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TRIGGERPARTICIPER
BEFORE INSERT ON PARTICIPER 
FOR EACH ROW 
BEGIN
    if inserting then
        :NEW.SCORE:=0;
        :NEW.TEMPS:=0;
    end if;
END;
/

CREATE OR REPLACE TRIGGER TRIGGERCHRONOMETRER
AFTER INSERT OR UPDATE OR DELETE ON CHRONOMETRER
FOR EACH ROW
DECLARE
    POSITION NUMBER(10, 0);
    TEMPS_MAX_EQUIPE NUMBER(10, 0);
    EQUIPE NUMBER(10, 0);
    EQUIPE_EXISTE NUMBER(10, 0);
    POSITION_EQUIPE NUMBER(10, 0);
BEGIN
    if updating or deleting then
        SELECT DISTINCT EQUIPE.ID_EQUIPE INTO EQUIPE FROM (((EPREUVE INNER JOIN COMPETITION ON EPREUVE.ID_COMPETITION=COMPETITION.ID_COMPETITION) 
        INNER JOIN PARTICIPER ON COMPETITION.ID_COMPETITION=PARTICIPER.ID_COMPETITION) INNER JOIN EQUIPE ON PARTICIPER.ID_EQUIPE=EQUIPE.ID_EQUIPE) INNER JOIN APPARTENIR ON EQUIPE.ID_EQUIPE=APPARTENIR.ID_EQUIPE WHERE APPARTENIR.ID_UTILISATEUR=:OLD.ID_UTILISATEUR;
        SELECT MAX(TEMPS) INTO TEMPS_MAX_EQUIPE FROM CLASSER_UTILISATEUR_EPREUVE, APPARTENIR WHERE APPARTENIR.ID_EQUIPE=EQUIPE AND CLASSER_UTILISATEUR_EPREUVE.ID_UTILISATEUR=APPARTENIR.ID_UTILISATEUR;
        DELETE FROM CLASSER_EQUIPE_EPREUVE WHERE ID_EPREUVE=:OLD.ID_EPREUVE AND ID_EQUIPE=EQUIPE;
        UPDATE CLASSER_EQUIPE_EPREUVE CEE SET CEE.POSITION=CEE.POSITION-1 WHERE ID_EPREUVE=:OLD.ID_EPREUVE AND TEMPS > TEMPS_MAX_EQUIPE;
    
        DELETE FROM CLASSER_UTILISATEUR_EPREUVE WHERE ID_EPREUVE=:OLD.ID_EPREUVE AND ID_UTILISATEUR=:OLD.ID_UTILISATEUR;
        UPDATE CLASSER_UTILISATEUR_EPREUVE SET POSITION=POSITION-1 WHERE ID_EPREUVE=:OLD.ID_EPREUVE AND TEMPS > :OLD.TEMPS;
    end if;
    if inserting or updating then
        SELECT COUNT(ID_UTILISATEUR)+1 INTO POSITION FROM CLASSER_UTILISATEUR_EPREUVE WHERE ID_EPREUVE=:NEW.ID_EPREUVE AND TEMPS < :NEW.TEMPS;
        INSERT INTO CLASSER_UTILISATEUR_EPREUVE(ID_UTILISATEUR, ID_EPREUVE, TEMPS, POSITION) VALUES (:NEW.ID_UTILISATEUR, :NEW.ID_EPREUVE, :NEW.TEMPS, POSITION);
        UPDATE CLASSER_UTILISATEUR_EPREUVE CUE SET CUE.POSITION=CUE.POSITION+1 WHERE ID_EPREUVE=:NEW.ID_EPREUVE AND TEMPS > :NEW.TEMPS;
        
        
        SELECT DISTINCT EQUIPE.ID_EQUIPE INTO EQUIPE FROM (((EPREUVE INNER JOIN COMPETITION ON EPREUVE.ID_COMPETITION=COMPETITION.ID_COMPETITION) 
        INNER JOIN PARTICIPER ON COMPETITION.ID_COMPETITION=PARTICIPER.ID_COMPETITION) INNER JOIN EQUIPE ON PARTICIPER.ID_EQUIPE=EQUIPE.ID_EQUIPE) INNER JOIN APPARTENIR ON EQUIPE.ID_EQUIPE=APPARTENIR.ID_EQUIPE WHERE APPARTENIR.ID_UTILISATEUR=:NEW.ID_UTILISATEUR;
        
        SELECT MAX(TEMPS) INTO TEMPS_MAX_EQUIPE FROM CLASSER_UTILISATEUR_EPREUVE, APPARTENIR WHERE APPARTENIR.ID_EQUIPE=EQUIPE AND CLASSER_UTILISATEUR_EPREUVE.ID_UTILISATEUR=APPARTENIR.ID_UTILISATEUR;
        SELECT COUNT(ID_EQUIPE)+1 INTO POSITION_EQUIPE FROM CLASSER_EQUIPE_EPREUVE WHERE ID_EPREUVE=:NEW.ID_EPREUVE AND TEMPS < TEMPS_MAX_EQUIPE;
        SELECT COUNT(ID_EQUIPE) INTO EQUIPE_EXISTE FROM CLASSER_EQUIPE_EPREUVE WHERE ID_EQUIPE=EQUIPE;
        
        if EQUIPE_EXISTE = 0 then
            INSERT INTO CLASSER_EQUIPE_EPREUVE VALUES(EQUIPE, :NEW.ID_EPREUVE, TEMPS_MAX_EQUIPE, POSITION_EQUIPE);
        else
            UPDATE CLASSER_EQUIPE_EPREUVE SET TEMPS=TEMPS_MAX_EQUIPE, POSITION=POSITION_EQUIPE WHERE ID_EQUIPE=EQUIPE AND ID_EPREUVE=:NEW.ID_EPREUVE;
        end if;
        UPDATE CLASSER_EQUIPE_EPREUVE CEE SET CEE.POSITION=CEE.POSITION+1 WHERE ID_EPREUVE=:NEW.ID_EPREUVE AND TEMPS > TEMPS_MAX_EQUIPE;
    end if;
END;
/

/*
Procedures
*/

CREATE OR REPLACE PROCEDURE GENERER_CODE_EQUIPE(ID_EQUIPE IN VARCHAR2)
IS
CODE2 VARCHAR2(10);
BEGIN
    SELECT dbms_random.string('A', 10) INTO CODE2 FROM DUAL;
    UPDATE EQUIPE SET CODE=CODE2 WHERE ID_EQUIPE=ID_EQUIPE;
END;
/

CREATE OR REPLACE PROCEDURE CREER_COMPETITION(NOM IN VARCHAR2, DATEFININSCRIPTION IN VARCHAR2, DATEDEBUT IN VARCHAR2,ID_TYPECOMPETITION IN NUMBER,ID_CATEGORIE IN NUMBER)
IS
BEGIN
    INSERT INTO COMPETITION(NOM, DATEFININSCRIPTION, DATEDEBUT, ID_TYPECOMPETITION, ID_CATEGORIE) VALUES (NOM, to_date(DATEFININSCRIPTION,'YYYY/MM/DD HH:MI:SS'), to_date(DATEDEBUT,'YYYY/MM/DD HH:MI:SS'), ID_TYPECOMPETITION, ID_CATEGORIE);
END;
/

CREATE OR REPLACE PROCEDURE INSCRIRE_UTILISATEUR(NOM IN VARCHAR2, PRENOM IN VARCHAR2, DATENAISSANCE IN DATE, NUMTELEPHONE IN VARCHAR2, CLUB IN VARCHAR2 DEFAULT NULL, EMAIL IN VARCHAR2, CODEPOSTAL IN VARCHAR2, VILLE IN VARCHAR2, ADRESSE IN VARCHAR2, MOTDEPASSE IN CHAR, ID_GENRE IN NUMBER, ID_RANG IN NUMBER)
IS
BEGIN
    INSERT INTO UTILISATEUR(NOM, PRENOM, DATENAISSANCE, NUMTELEPHONE, CLUB, EMAIL, CODEPOSTAL, VILLE, ADRESSE, MOTDEPASSE, ID_GENRE, ID_RANG) VALUES (NOM, PRENOM, DATENAISSANCE, NUMTELEPHONE, CLUB, EMAIL, CODEPOSTAL, VILLE, ADRESSE, MOTDEPASSE, ID_GENRE, ID_RANG);
END;
/

CREATE OR REPLACE PROCEDURE AJOUTER_PARTICIPANT_EQUIPE(ID_UTILISATEUR NUMBER, ID_EQUIPE NUMBER, ID_ROLEEQUIPE NUMBER)
IS
BEGIN
    INSERT INTO APPARTENIR(ID_UTILISATEUR, ID_EQUIPE, ID_ROLEEQUIPE) VALUES (ID_UTILISATEUR, ID_EQUIPE, ID_ROLEEQUIPE);
END;
/

CREATE OR REPLACE PROCEDURE AJOUTER_PARTICIPATION_EQUIPE(ID_COMPETITION NUMBER, ID_EQUIPE NUMBER)
IS
BEGIN 
    INSERT INTO PARTICIPER(ID_COMPETITION, ID_EQUIPE) VALUES (ID_COMPETITION, ID_EQUIPE);
END;
/

CREATE OR REPLACE PROCEDURE CREER_EQUIPE(nom VARCHAR2)
IS
BEGIN
    INSERT INTO EQUIPE(NOM) values (nom);
END;
/

CREATE OR REPLACE PROCEDURE ENREGISTRER_TEMPS(utilisateur NUMBER, epreuve NUMBER, temps NUMBER)
IS 
BEGIN
    INSERT INTO CHRONOMETRER VALUES (utilisateur, epreuve, temps);
END;
/

/*
Fonctions
*/

CREATE OR REPLACE FUNCTION VERIF_EMAIL_DEJA_UTIL (PARAM_EMAIL IN VARCHAR2) RETURN NUMBER
IS
NBR_PRESENCE NUMBER(1);
BEGIN
    SELECT COUNT(ID_UTILISATEUR)
    INTO NBR_PRESENCE
    FROM UTILISATEUR
    WHERE EMAIL = PARAM_EMAIL;
    RETURN NBR_PRESENCE;
END;
/
/*
Valeurs par défaut
*/

INSERT INTO RANG(LIBELLE) VALUES ('Participant');
INSERT INTO RANG(LIBELLE) VALUES ('Tresorier');
INSERT INTO RANG(LIBELLE) VALUES ('Secretaire');
INSERT INTO RANG(LIBELLE) VALUES ('Administrateur');

INSERT INTO CATEGORIE(LIBELLE) VALUES ('Hommes');
INSERT INTO CATEGORIE(LIBELLE) VALUES ('Femmes');
INSERT INTO CATEGORIE(LIBELLE) VALUES ('Mixte');

INSERT INTO GENRE(LIBELLE) VALUES ('Homme');
INSERT INTO GENRE(LIBELLE) VALUES ('Femme');

INSERT INTO TYPEPIECEJOINTE(LIBELLE) VALUES ('Licence');
INSERT INTO TYPEPIECEJOINTE(LIBELLE) VALUES ('Certificat médical');
INSERT INTO TYPEPIECEJOINTE(LIBELLE) VALUES ('Autorisation parentale');
INSERT INTO TYPEPIECEJOINTE(LIBELLE) VALUES ('Autre');

INSERT INTO ROLEEQUIPE(LIBELLE) VALUES ('Capitaine');
INSERT INTO ROLEEQUIPE(LIBELLE) VALUES ('Equipier');

INSERT INTO TYPECOMPETITION(LIBELLE) VALUES ('Bol d''Air');
INSERT INTO TYPECOMPETITION(LIBELLE) VALUES ('Mini Bol d''Air');
INSERT INTO TYPECOMPETITION(LIBELLE) VALUES ('Bol d''Eau');
INSERT INTO TYPECOMPETITION(LIBELLE) VALUES ('Mini Bol d''Eau');

INSERT INTO TYPEEPREUVE(LIBELLE) VALUES ('Course à pied');
INSERT INTO TYPEEPREUVE(LIBELLE) VALUES ('Canoe');
INSERT INTO TYPEEPREUVE(LIBELLE) VALUES ('VTT');

/*
Jeu d'essai
*/

INSERT INTO COMPETITION(NOM, DATEFININSCRIPTION, DATEDEBUT, ID_TYPECOMPETITION, ID_CATEGORIE) VALUES ('Bol d''Air Juillet 2018 Mixte', TO_DATE('2018/07/2 1:00:00', 'YYYY/MM/DD HH:MI:SS'), TO_DATE('2018/07/02 2:00:00', 'YYYY/MM/DD HH:MI:SS'), 1, 3);
INSERT INTO COMPETITION(NOM, DATEFININSCRIPTION, DATEDEBUT, ID_TYPECOMPETITION, ID_CATEGORIE) VALUES ('Mini Bol d''Air Juillet 2018 Mixte', TO_DATE('2018/07/9 1:00:00', 'YYYY/MM/DD HH:MI:SS'), TO_DATE('2018/07/09 2:00:00', 'YYYY/MM/DD HH:MI:SS'), 3, 3);

INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(1, 1, 1);
INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(2, 2, 1);
INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(3, 3, 1);

INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(1, 3, 2);
INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(2, 2, 2);
INSERT INTO EPREUVE(ORDRE, ID_TYPEEPREUVE, ID_COMPETITION) VALUES(3, 1, 2);

INSERT INTO UTILISATEUR(NOM, PRENOM, DATENAISSANCE, NUMTELEPHONE, CLUB, EMAIL, CODEPOSTAL, VILLE, ADRESSE, MOTDEPASSE, ID_GENRE) VALUES ('avecclub', 'jean', to_date('1970-07-09', 'yyyy-MM-dd'), '0123456789', 'Club', 'a@a.com', '11111', 'Oui', 'Avenue du oui', 'aaaaaa', 1);
INSERT INTO UTILISATEUR(NOM, PRENOM, DATENAISSANCE, NUMTELEPHONE, EMAIL, CODEPOSTAL, VILLE, ADRESSE, MOTDEPASSE, ID_GENRE) VALUES ('sansclub', 'jean', to_date('1970-07-09', 'yyyy-MM-dd'), '0123456789', '11111', 'b@a.com', 'Oui', 'Avenue du oui', 'aaaaaa', 2);
INSERT INTO UTILISATEUR(NOM, PRENOM, DATENAISSANCE, NUMTELEPHONE, EMAIL, CODEPOSTAL, VILLE, ADRESSE, MOTDEPASSE, ID_GENRE, ID_RANG) VALUES ('Dang', 'xavier', to_date('1970-07-09', 'yyyy-MM-dd'), '0123456789', 'c@a.com', '11111', 'Oui', 'Avenue du oui', 'aaaaaa', 1, 4);

INSERT INTO EQUIPE(NOM) VALUES ('Le Zoo');
INSERT INTO EQUIPE(NOM) VALUES ('Les gardiens du Zoo');

execute AJOUTER_PARTICIPANT_EQUIPE(1, 1, 1);
execute AJOUTER_PARTICIPANT_EQUIPE(2, 1, 2);

execute AJOUTER_PARTICIPANT_EQUIPE(3, 2, 1);

execute AJOUTER_PARTICIPATION_EQUIPE(1, 1);
execute AJOUTER_PARTICIPATION_EQUIPE(1, 2);

EXECUTE ENREGISTRER_TEMPS(1, 1, 7200);
INSERT INTO CHRONOMETRER(ID_UTILISATEUR, ID_EPREUVE, TEMPS) VALUES (2, 1, 3600);
INSERT INTO CHRONOMETRER(ID_UTILISATEUR, ID_EPREUVE, TEMPS) VALUES (3, 1, 4800);

UPDATE CHRONOMETRER SET TEMPS=10000 WHERE ID_EPREUVE=1 AND ID_UTILISATEUR=3;

DELETE FROM CHRONOMETRER WHERE ID_UTILISATEUR=2 AND ID_EPREUVE=1;

/*
Tests de procédures
*/

execute GENERER_CODE_EQUIPE(1);

execute CREER_COMPETITION('moer','2018/07/9 1:00:00','2018/07/9 1:00:00',1,2);

execute INSCRIRE_UTILISATEUR('Nom', 'Prenom', TO_DATE('2018/07/2 1:00:00', 'YYYY/MM/DD HH:MI:SS'), '0123456789', null, 'd@a.com', '11111', 'Ville', 'rue oui', 'aaaaaa', 1, 1);

EXECUTE CREER_EQUIPE('zabouza');

EXECUTE ENREGISTRER_TEMPS(264);
/*
Tests de fonctions
*/

SELECT VERIF_EMAIL_DEJA_UTIL('a@a.com') FROM DUAL;

SELECT VERIF_EMAIL_DEJA_UTIL('e@a.com') FROM DUAL;