#------------------------------------------------------------
# Table: CATEGORIE
#------------------------------------------------------------

CREATE TABLE CATEGORIE(
    ID_CATEGORIE SERIAL NOT NULL ,
    LIBELLE      VARCHAR2(20) NOT NULL ,
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (ID_CATEGORIE)
);


#------------------------------------------------------------
# Table: RANG
#------------------------------------------------------------

CREATE TABLE RANG(
    ID_RANG SERIAL  NOT NULL ,
    LIBELLE VARCHAR2(25) NOT NULL ,
    CONSTRAINT PK_RANG PRIMARY KEY (ID_RANG)
);


#------------------------------------------------------------
# Table: GENRE
#------------------------------------------------------------

CREATE TABLE GENRE(
    ID_GENRE SERIAL  NOT NULL ,
    LIBELLE  VARCHAR2(20) NOT NULL ,
    CONSTRAINT PK_GENRE PRIMARY KEY (ID_GENRE)
);


#------------------------------------------------------------
# Table: TYPEPIECEJOINTE
#------------------------------------------------------------

CREATE TABLE TYPEPIECEJOINTE(
    ID_TYPEPIECEJOINTE SERIAL  NOT NULL ,
    LIBELLE            VARCHAR2(25) NOT NULL ,
    CONSTRAINT PK_TYPEPIECEJOINTE PRIMARY KEY (ID_TYPEPIECEJOINTE)
);


#------------------------------------------------------------
# Table: EQUIPE
#------------------------------------------------------------

CREATE TABLE EQUIPE(
    ID_EQUIPE SERIAL NOT NULL ,
    NOM       VARCHAR2(25) NOT NULL ,
    CODE      VARCHAR2(10) NOT NULL ,
    VALIDE    Char (1) NOT NULL ,
    CONSTRAINT PK_EQUIPE PRIMARY KEY (ID_EQUIPE)
);


#------------------------------------------------------------
# Table: ROLEEQUIPE
#------------------------------------------------------------

CREATE TABLE ROLEEQUIPE(
    ID_ROLEEQUIPE SERIAL NOT NULL ,
    LIBELLE       VARCHAR2(25) NOT NULL ,
    CONSTRAINT PK_ROLEEQUIPE PRIMARY KEY (ID_ROLEEQUIPE)
);


#------------------------------------------------------------
# Table: UTILISATEUR
#------------------------------------------------------------

CREATE TABLE UTILISATEUR(
    ID_UTILISATEUR SERIAL NOT NULL ,
    NOM            VARCHAR2(25) NOT NULL ,
    PRENOM         VARCHAR2(25) NOT NULL ,
    DATENAISSANCE  DATE NOT NULL ,
    NUMTELEPHONE   VARCHAR2(25) NOT NULL ,
    CLUB           VARCHAR2(25) NOT NULL ,
    EMAIL          VARCHAR2(25) NOT NULL ,
    CODEPOSTAL     VARCHAR2(25) NOT NULL ,
    VILLE          VARCHAR2(25) NOT NULL ,
    ADRESSE        VARCHAR2(25) NOT NULL ,
    ID_GENRE       SERIAL NOT NULL ,
    ID_RANG        SERIAL NOT NULL ,
    ID_EQUIPE      SERIAL NOT NULL ,
    ID_ROLEEQUIPE  SERIAL NOT NULL ,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY (ID_UTILISATEUR) ,
    CONSTRAINT FK_UTILISATEUR_GENRE FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE) ,
    CONSTRAINT FK_UTILISATEUR_RANG FOREIGN KEY (ID_RANG) REFERENCES RANG(ID_RANG) ,
    CONSTRAINT FK_UTILISATEUR_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ,
    CONSTRAINT FK_UTILISATEUR_ROLEEQUIPE FOREIGN KEY (ID_ROLEEQUIPE) REFERENCES ROLEEQUIPE(ID_ROLEEQUIPE)
);


#------------------------------------------------------------
# Table: PIECEJOINTE
#------------------------------------------------------------

CREATE TABLE PIECEJOINTE(
    ID_PIECEJOINTE     SERIAL NOT NULL ,
    LIBELLE            VARCHAR2(25) NOT NULL ,
    CHEMIN             VARCHAR2(25) NOT NULL ,
    ID_UTILISATEUR     SERIAL NOT NULL ,
    ID_TYPEPIECEJOINTE SERIAL NOT NULL ,
    CONSTRAINT PK_PIECEJOINTE PRIMARY KEY (ID_PIECEJOINTE) ,
    CONSTRAINT FK_PIECEJOINTE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_PIECEJOINTE_ROLEEQUIPE FOREIGN KEY (ID_TYPEPIECEJOINTE) REFERENCES ROLEEQUIPE(ID_ROLEEQUIPE)
);


#------------------------------------------------------------
# Table: TYPECOMPETITION
#------------------------------------------------------------

CREATE TABLE TYPECOMPETITION(
    ID_TYPECOMPETITION SERIAL NOT NULL ,
    LIBELLE            VARCHAR2(25) NOT NULL ,
    CONSTRAINT PK_TYPECOMPETITION PRIMARY KEY (ID_TYPECOMPETITION)
);


#------------------------------------------------------------
# Table: COMPETITION
#------------------------------------------------------------

CREATE TABLE COMPETITION(
    ID_COMPETITION     SERIAL NOT NULL ,
    NOM                VARCHAR2(25) NOT NULL ,
    DateFinInscription DATE NOT NULL ,
    DateDebut          DATE NOT NULL ,
    ID_TYPECOMPETITION SERIAL NOT NULL ,
    ID_CATEGORIE       SERIAL NOT NULL ,
    CONSTRAINT PK_COMPETITION PRIMARY KEY (ID_COMPETITION),
    CONSTRAINT FK_COMPETITION_TYPECOMPETITION FOREIGN KEY (ID_TYPECOMPETITION) REFERENCES TYPECOMPETITION(ID_TYPECOMPETITION)
);


#------------------------------------------------------------
# Table: TYPEEPREUVE
#------------------------------------------------------------

CREATE TABLE TYPEEPREUVE(
    ID_TYPEEPREUVE SERIAL NOT NULL ,
    LIBELLE        VARCHAR2(25) NOT NULL ,
    CONSTRAINT PK_TYPEEPREUVE PRIMARY KEY (ID_TYPEEPREUVE)
);


#------------------------------------------------------------
# Table: EPREUVE
#------------------------------------------------------------

CREATE TABLE EPREUVE(
    ID_EPREUVE     SERIAL  NOT NULL ,
    ORDRE          INT NOT NULL ,
    ID_TYPEEPREUVE SERIAL NOT NULL ,
    ID_COMPETITION SERIAL NOT NULL ,
    CONSTRAINT PK_EPREUVE PRIMARY KEY (ID_EPREUVE) ,
    CONSTRAINT FK_EPREUVE_TYPEEPREUVE FOREIGN KEY (ID_TYPEEPREUVE) REFERENCES TYPEEPREUVE(ID_TYPEEPREUVE) ,
    CONSTRAINT FK_EPREUVE_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION)
);

#------------------------------------------------------------
# Table: PARTICIPER
#------------------------------------------------------------

CREATE TABLE PARTICIPER(
    ID_COMPETITION SERIAL NOT NULL ,
    ID_EQUIPE      SERIAL NOT NULL ,
    SCORE          INT ,
    CONSTRAINT PK_PARTICIPER PRIMARY KEY (ID_COMPETITION, ID_EQUIPE) ,
    CONSTRAINT FK_PARTICIPER_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION) ,
    CONSTRAINT FK_PARTICIPER_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE)
);


#------------------------------------------------------------
# Table: CHRONOMETRER
#------------------------------------------------------------

CREATE TABLE CHRONOMETRER(
    TEMPS          INT NOT NULL ,
    ID_UTILISATEUR SERIAL NOT NULL ,
    ID_EPREUVE     SERIAL NOT NULL ,
    CONSTRAINT PK_CHRONOMETRER PRIMARY KEY (ID_UTILISATEUR, ID_EPREUVE) ,
    CONSTRAINT FK_CHRONOMETRER_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_CHRONOMETRER_EPREUVE FOREIGN KEY (ID_EPREUVE) REFERENCES EPREUVE(ID_EPREUVE)
);


#------------------------------------------------------------
# Table: ASSOCIER
#------------------------------------------------------------

CREATE TABLE ASSOCIER(
    DOSSARD        INT ,
    PUCE           INT ,
    ID_UTILISATEUR SERIAL NOT NULL ,
    ID_COMPETITION SERIAL NOT NULL ,
    CONSTRAINT PK_ASSOCIER PRIMARY KEY (ID_UTILISATEUR, ID_COMPETITION) ,
    CONSTRAINT FK_ASSOCIER_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR) ,
    CONSTRAINT FK_ASSOCIER_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION)
);

#------------------------------------------------------------
# Table: CLASSEMENT
#------------------------------------------------------------

CREATE TABLE CLASSEMENT(
    ID_CLASSEMENT SERIAL NOT NULL ,
    LIBELLE       VARCHAR2 (255) NOT NULL ,
    CONSTRAINT PK_CLASSEMENT PRIMARY KEY (ID_CLASSEMENT)
);

#------------------------------------------------------------
# Table: CLASSER
#------------------------------------------------------------

CREATE TABLE CLASSER(
    POSITION      INT NOT NULL ,
    ID_EQUIPE     SERIAL NOT NULL ,
    ID_CLASSEMENT SERIAL NOT NULL ,
    CONSTRAINT PK_CLASSER PRIMARY KEY (ID_EQUIPE, ID_CLASSEMENT)
);

/*
ALTER TABLE Utilisateur ADD CONSTRAINT FK_Utilisateur_ID_RANG FOREIGN KEY (ID_RANG) REFERENCES Rang(ID_RANG);
ALTER TABLE Utilisateur ADD CONSTRAINT FK_Utilisateur_ID_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES Equipe(ID_EQUIPE);
ALTER TABLE Utilisateur ADD CONSTRAINT FK_Utilisateur_ID_ROLEEQUIPE FOREIGN KEY (ID_ROLEEQUIPE) REFERENCES RoleEquipe(ID_ROLEEQUIPE);
ALTER TABLE PieceJointe ADD CONSTRAINT FK_PieceJointe_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES Utilisateur(ID_UTILISATEUR);
ALTER TABLE PieceJointe ADD CONSTRAINT FK_PieceJointe_ID_TYPEPIECEJOINTE FOREIGN KEY (ID_TYPEPIECEJOINTE) REFERENCES TypePieceJointe(ID_TYPEPIECEJOINTE);
ALTER TABLE Competition ADD CONSTRAINT FK_Competition_ID_TYPECOMPETITION FOREIGN KEY (ID_TYPECOMPETITION) REFERENCES TypeCompetition(ID_TYPECOMPETITION);
ALTER TABLE Competition ADD CONSTRAINT FK_Competition_ID_GENRE FOREIGN KEY (ID_GENRE) REFERENCES Genre(ID_GENRE);
ALTER TABLE Epreuve ADD CONSTRAINT FK_Epreuve_ID_TYPEEPREUVE FOREIGN KEY (ID_TYPEEPREUVE) REFERENCES TypeEpreuve(ID_TYPEEPREUVE);
ALTER TABLE Epreuve ADD CONSTRAINT FK_Epreuve_ID_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES Competition(ID_COMPETITION);
ALTER TABLE PARTICIPER ADD CONSTRAINT FK_PARTICIPER_ID_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES Competition(ID_COMPETITION);
ALTER TABLE PARTICIPER ADD CONSTRAINT FK_PARTICIPER_ID_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES Equipe(ID_EQUIPE);
ALTER TABLE CHRONOMETRER ADD CONSTRAINT FK_CHRONOMETRER_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES Utilisateur(ID_UTILISATEUR);
ALTER TABLE CHRONOMETRER ADD CONSTRAINT FK_CHRONOMETRER_ID_EPREUVE FOREIGN KEY (ID_EPREUVE) REFERENCES Epreuve(ID_EPREUVE);
ALTER TABLE ASSOCIER ADD CONSTRAINT FK_ASSOCIER_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES Utilisateur(ID_UTILISATEUR);
ALTER TABLE ASSOCIER ADD CONSTRAINT FK_ASSOCIER_ID_COMPETITION FOREIGN KEY (ID_COMPETITION) REFERENCES Competition(ID_COMPETITION);
*/